/**
 * NativeGateway is the only dashboard import surface for desktop IPC,
 * shell window helpers, runtime capabilities, and shell telemetry.
 */
export { invokeDesktopCommand, openDesktopExternalUrl, openDesktopExternalUrlWithFallback } from "@/lib/desktop-bridge/commands";
export {
  hasDesktopTauriIpcBridge,
  isDesktopTauriRuntime,
} from "@/lib/desktop-bridge/environment";
export {
  ensureMicrophonePermission,
  isTauri,
  showMainWindow,
  openInBrowser,
  openInBrowserFromDesktopAuth,
  openDesktopSettingsWindow,
  openDesktopVoiceHud,
  hideDesktopVoiceHud,
  getVoiceHotkeySettings,
  setVoiceHotkeySettings,
  syncSidebarGlassWidth,
  startWindowResizeDragging,
  resizeWindow,
  restoreDashboardWindowSize,
  setStandardWindowSize,
  setOnboardingWindowSize,
  setDashboardWindowSize,
  ONBOARDING_WINDOW_WIDTH,
  ONBOARDING_WINDOW_HEIGHT,
  ONBOARDING_HOME_WINDOW_WIDTH,
  ONBOARDING_HOME_WINDOW_HEIGHT,
  ONBOARDING_WELCOME_WINDOW_WIDTH,
  ONBOARDING_WELCOME_WINDOW_HEIGHT,
  ONBOARDING_SETUP_WINDOW_WIDTH,
  ONBOARDING_SETUP_WINDOW_HEIGHT,
  ONBOARDING_SIGNUP_WINDOW_WIDTH,
  ONBOARDING_SIGNUP_WINDOW_HEIGHT,
  ONBOARDING_CARD_WINDOW_WIDTH,
  ONBOARDING_CARD_WINDOW_HEIGHT,
  type DesktopSettingsView,
  type OpenDesktopVoiceHudPayload,
  type VoiceHotkeySettings,
  type WindowResizeDirection,
} from "@/lib/desktop-bridge/shell";
export {
  buildDesktopCommandOrigin,
  checkDesktopForUpdates,
  clearDesktopRuntimeInfoCache,
  compareDesktopVersions,
  desktopHasCapability,
  desktopBeginAuthHandoff,
  desktopCompleteAuthHandoff,
  desktopGetAuthToken,
  desktopSetAuthToken,
  desktopSetPrivacyState,
  desktopSetComputerTracking,
  desktopSetLaunchAtLogin,
  desktopSetMenuBarVisibility,
  desktopQuitCompletely,
  syncComputerActivityNow,
  desktopClearAuthState,
  desktopFrontendReady,
  getDesktopCompatibilityIssue,
  getDesktopRuntimeInfo,
  getDesktopRuntimeState,
  getDesktopResidentRuntimeState,
  getDesktopDiagnostics,
  installDesktopUpdate,
  readDesktopCompatibilityRequirements,
  type DesktopRuntimeInfo,
  type DesktopAuthHandoffStart,
  type DesktopNativeAuthSession,
  type DesktopRuntimeState,
  type DesktopDiagnostics,
  type DesktopProcessMetrics,
  type DesktopComputerSyncStage,
  type ComputerActivitySyncResult,
  type DesktopResidentRuntimeState,
  type DesktopWatcherConfig,
  type DesktopCompatibilityIssue,
  type UpdateManifest,
} from "@/lib/desktop-bridge/runtime";
export {
  recordDesktopShellEvent,
  recordLaunchMilestone,
  getLaunchMilestones,
  summarizeLaunchMilestones,
  type DesktopShellEventLevel,
  type LaunchMedianSummary,
} from "@/lib/desktop-bridge/observability";
export {
  NATIVE_COMMANDS,
  NATIVE_COMMAND_CAPABILITIES,
  isNativeCommandName,
  type NativeCommandName,
  type NativeCommandCapability,
  type NativeCommandInputs,
  type NativeCommandOutputs,
  type NativeCommandContract,
} from "@/lib/native-gateway-commands.generated";
