// Generated by scripts/check-tauri-command-acl.mjs. Do not edit.
export const NATIVE_COMMANDS = [
  "check_accessibility_permission",
  "check_dashboard_refresh_trigger",
  "check_native_microphone_permission",
  "check_native_speech_recognition_permission",
  "check_runtime_bridge_signals",
  "check_token_refresh_request",
  "clear_native_speech_state",
  "clear_watcher_config_cmd",
  "desktop_begin_auth_handoff",
  "desktop_capture_sentry_smoke",
  "desktop_clear_auth_state",
  "desktop_complete_auth_handoff",
  "desktop_frontend_ready",
  "desktop_install_update",
  "desktop_manual_update_check",
  "desktop_record_shell_event",
  "desktop_set_auth_token",
  "desktop_set_privacy_state",
  "desktop_trigger_biome_iphone_sync",
  "get_app_icon",
  "get_app_icons_batch",
  "get_biome_iphone_diagnostics",
  "get_browser_extension_diagnostics",
  "get_daily_summaries",
  "get_desktop_diagnostics",
  "get_desktop_runtime_info",
  "get_desktop_runtime_state",
  "get_desktop_shell_bootstrap_config",
  "get_detailed_activity",
  "get_local_computer_activity_snapshot",
  "get_native_speech_state",
  "get_project_time_attribution_health",
  "get_voice_hotkey_settings",
  "get_watcher_status",
  "hide_voice_hud",
  "import_biome_iphone_export",
  "init_ritual_database",
  "open_accessibility_settings",
  "open_full_disk_access_settings",
  "open_location_settings",
  "open_microphone_settings",
  "open_screen_recording_settings",
  "open_settings_window",
  "open_speech_recognition_settings",
  "open_voice_hud",
  "reconcile_watcher_config_user_cmd",
  "request_accessibility_permission",
  "save_watcher_config_cmd",
  "set_voice_hotkey_settings",
  "show_main_window",
  "show_native_microphone_permission_dialog",
  "show_native_speech_recognition_permission_dialog",
  "sidebar_get_main_state",
  "sidebar_navigate",
  "sidebar_set_width",
  "start_native_speech_recognition",
  "start_watcher",
  "stop_native_speech_recognition",
  "stop_watcher",
  "sync_computer_activity_now",
  "update_voice_hud_state",
  "vault_compare_and_swap",
  "vault_get_record",
  "vault_get_status",
  "vault_initialize",
  "vault_list_deletion_receipts",
  "vault_list_migration_manifests",
  "vault_list_records",
  "vault_list_records_page",
  "vault_put_deletion_receipt",
  "vault_put_migration_manifest",
  "vault_put_record",
  "vault_tombstone_record",
  "write_auth_token_to_file",
] as const;

export type NativeCommandName = (typeof NATIVE_COMMANDS)[number];

export const NATIVE_COMMAND_CAPABILITIES = {
  "check_accessibility_permission": "desktop-activity",
  "check_dashboard_refresh_trigger": "desktop-runtime",
  "check_native_microphone_permission": "desktop-activity",
  "check_native_speech_recognition_permission": "desktop-activity",
  "check_runtime_bridge_signals": "desktop-runtime",
  "check_token_refresh_request": "desktop-runtime",
  "clear_native_speech_state": "desktop-runtime",
  "clear_watcher_config_cmd": "desktop-activity",
  "desktop_begin_auth_handoff": "desktop-runtime",
  "desktop_capture_sentry_smoke": "desktop-observability",
  "desktop_clear_auth_state": "desktop-runtime",
  "desktop_complete_auth_handoff": "desktop-runtime",
  "desktop_frontend_ready": "desktop-runtime",
  "desktop_install_update": "desktop-runtime",
  "desktop_manual_update_check": "desktop-runtime",
  "desktop_record_shell_event": "desktop-shell-bootstrap",
  "desktop_set_auth_token": "desktop-runtime",
  "desktop_set_privacy_state": "desktop-runtime",
  "desktop_trigger_biome_iphone_sync": "desktop-runtime",
  "get_app_icon": "desktop-activity",
  "get_app_icons_batch": "desktop-activity",
  "get_biome_iphone_diagnostics": "desktop-runtime",
  "get_browser_extension_diagnostics": "desktop-activity",
  "get_daily_summaries": "desktop-activity",
  "get_desktop_diagnostics": "desktop-runtime",
  "get_desktop_runtime_info": "desktop-runtime",
  "get_desktop_runtime_state": "desktop-runtime",
  "get_desktop_shell_bootstrap_config": "desktop-shell-bootstrap",
  "get_detailed_activity": "desktop-activity",
  "get_local_computer_activity_snapshot": "desktop-activity",
  "get_native_speech_state": "desktop-runtime",
  "get_project_time_attribution_health": "desktop-activity",
  "get_voice_hotkey_settings": "desktop-shell-ui",
  "get_watcher_status": "desktop-activity",
  "hide_voice_hud": "desktop-shell-ui",
  "import_biome_iphone_export": "desktop-runtime",
  "init_ritual_database": "desktop-activity",
  "open_accessibility_settings": "desktop-activity",
  "open_full_disk_access_settings": "desktop-activity",
  "open_location_settings": "desktop-activity",
  "open_microphone_settings": "desktop-activity",
  "open_screen_recording_settings": "desktop-activity",
  "open_settings_window": "desktop-shell-bootstrap",
  "open_speech_recognition_settings": "desktop-activity",
  "open_voice_hud": "desktop-shell-ui",
  "reconcile_watcher_config_user_cmd": "desktop-activity",
  "request_accessibility_permission": "desktop-activity",
  "save_watcher_config_cmd": "desktop-activity",
  "set_voice_hotkey_settings": "desktop-shell-ui",
  "show_main_window": "desktop-shell-bootstrap",
  "show_native_microphone_permission_dialog": "desktop-activity",
  "show_native_speech_recognition_permission_dialog": "desktop-activity",
  "sidebar_get_main_state": "desktop-shell-ui",
  "sidebar_navigate": "desktop-shell-ui",
  "sidebar_set_width": "desktop-shell-ui",
  "start_native_speech_recognition": "desktop-runtime",
  "start_watcher": "desktop-activity",
  "stop_native_speech_recognition": "desktop-runtime",
  "stop_watcher": "desktop-activity",
  "sync_computer_activity_now": "desktop-runtime",
  "update_voice_hud_state": "desktop-shell-ui",
  "vault_compare_and_swap": "desktop-vault",
  "vault_get_record": "desktop-vault",
  "vault_get_status": "desktop-vault",
  "vault_initialize": "desktop-vault",
  "vault_list_deletion_receipts": "desktop-vault",
  "vault_list_migration_manifests": "desktop-vault",
  "vault_list_records": "desktop-vault",
  "vault_list_records_page": "desktop-vault",
  "vault_put_deletion_receipt": "desktop-vault",
  "vault_put_migration_manifest": "desktop-vault",
  "vault_put_record": "desktop-vault",
  "vault_tombstone_record": "desktop-vault",
  "write_auth_token_to_file": "desktop-runtime",
} as const;

export type NativeCommandCapability = (typeof NATIVE_COMMAND_CAPABILITIES)[NativeCommandName];

export type NativeCommandInputs = {
  check_accessibility_permission: Record<string, never>;
  check_dashboard_refresh_trigger: Record<string, never>;
  check_native_microphone_permission: Record<string, never>;
  check_native_speech_recognition_permission: Record<string, never>;
  check_runtime_bridge_signals: Record<string, never>;
  check_token_refresh_request: Record<string, never>;
  clear_native_speech_state: Record<string, never>;
  clear_watcher_config_cmd: Record<string, never>;
  desktop_begin_auth_handoff: Record<string, never>;
  desktop_capture_sentry_smoke: Record<string, never>;
  desktop_clear_auth_state: Record<string, never>;
  desktop_complete_auth_handoff: { handoffId: string };
  desktop_frontend_ready: Record<string, never>;
  desktop_install_update: Record<string, never>;
  desktop_manual_update_check: Record<string, never>;
  desktop_record_shell_event: { name: string; level?: string | null; data?: unknown | null };
  desktop_set_auth_token: { token: string; userId?: string | null; backendBase?: string | null };
  desktop_set_privacy_state: { state: unknown };
  desktop_trigger_biome_iphone_sync: Record<string, never>;
  get_app_icon: { bundleId: string };
  get_app_icons_batch: { bundleIds: Array<string> };
  get_biome_iphone_diagnostics: Record<string, never>;
  get_browser_extension_diagnostics: Record<string, never>;
  get_daily_summaries: { startDate: string; endDate: string; origin?: string | null };
  get_desktop_diagnostics: Record<string, never>;
  get_desktop_runtime_info: Record<string, never>;
  get_desktop_runtime_state: Record<string, never>;
  get_desktop_shell_bootstrap_config: Record<string, never>;
  get_detailed_activity: { startTs: number; endTs: number; limit?: number | null; origin?: string | null };
  get_local_computer_activity_snapshot: { startDate: string; endDate: string; limit?: number | null; origin?: string | null };
  get_native_speech_state: Record<string, never>;
  get_project_time_attribution_health: { origin?: string | null };
  get_voice_hotkey_settings: Record<string, never>;
  get_watcher_status: Record<string, never>;
  hide_voice_hud: Record<string, never>;
  import_biome_iphone_export: { path: string };
  init_ritual_database: { origin?: string | null };
  open_accessibility_settings: Record<string, never>;
  open_full_disk_access_settings: Record<string, never>;
  open_location_settings: Record<string, never>;
  open_microphone_settings: Record<string, never>;
  open_screen_recording_settings: Record<string, never>;
  open_settings_window: { initialView?: string | null };
  open_speech_recognition_settings: Record<string, never>;
  open_voice_hud: { target: string; source?: string | null; submitOnFinal?: boolean | null; anchorRect?: unknown | null };
  reconcile_watcher_config_user_cmd: { userId: string };
  request_accessibility_permission: Record<string, never>;
  save_watcher_config_cmd: { config: unknown };
  set_voice_hotkey_settings: { settings: unknown };
  show_main_window: Record<string, never>;
  show_native_microphone_permission_dialog: Record<string, never>;
  show_native_speech_recognition_permission_dialog: Record<string, never>;
  sidebar_get_main_state: Record<string, never>;
  sidebar_navigate: { path: string };
  sidebar_set_width: { width: number };
  start_native_speech_recognition: Record<string, never>;
  start_watcher: { config: unknown };
  stop_native_speech_recognition: Record<string, never>;
  stop_watcher: Record<string, never>;
  sync_computer_activity_now: Record<string, never>;
  update_voice_hud_state: { state: unknown };
  vault_compare_and_swap: { input: unknown };
  vault_get_record: { userId: string; collection: string; recordId: string };
  vault_get_status: { userId?: string | null };
  vault_initialize: { userId: string };
  vault_list_deletion_receipts: { userId: string; limit?: number | null };
  vault_list_migration_manifests: { userId: string; limit?: number | null };
  vault_list_records: { userId: string; collection: string; since?: string | null; limit?: number | null };
  vault_list_records_page: { userId: string; collection: string; cursor?: string | null; limit?: number | null };
  vault_put_deletion_receipt: { input: unknown };
  vault_put_migration_manifest: { input: unknown };
  vault_put_record: { input: unknown };
  vault_tombstone_record: { userId: string; collection: string; recordId: string; recordType: string };
  write_auth_token_to_file: { token: string; origin?: string | null };
};

export type NativeCommandOutputs = {
  check_accessibility_permission: boolean;
  check_dashboard_refresh_trigger: number;
  check_native_microphone_permission: boolean;
  check_native_speech_recognition_permission: boolean;
  check_runtime_bridge_signals: unknown;
  check_token_refresh_request: number;
  clear_native_speech_state: void;
  clear_watcher_config_cmd: void;
  desktop_begin_auth_handoff: unknown;
  desktop_capture_sentry_smoke: void;
  desktop_clear_auth_state: unknown;
  desktop_complete_auth_handoff: void;
  desktop_frontend_ready: unknown;
  desktop_install_update: void;
  desktop_manual_update_check: unknown;
  desktop_record_shell_event: void;
  desktop_set_auth_token: unknown;
  desktop_set_privacy_state: unknown;
  desktop_trigger_biome_iphone_sync: unknown;
  get_app_icon: unknown;
  get_app_icons_batch: Array<unknown>;
  get_biome_iphone_diagnostics: unknown;
  get_browser_extension_diagnostics: unknown;
  get_daily_summaries: Array<unknown>;
  get_desktop_diagnostics: unknown;
  get_desktop_runtime_info: unknown;
  get_desktop_runtime_state: unknown;
  get_desktop_shell_bootstrap_config: unknown;
  get_detailed_activity: unknown;
  get_local_computer_activity_snapshot: unknown;
  get_native_speech_state: unknown;
  get_project_time_attribution_health: unknown;
  get_voice_hotkey_settings: unknown;
  get_watcher_status: unknown;
  hide_voice_hud: void;
  import_biome_iphone_export: unknown;
  init_ritual_database: string;
  open_accessibility_settings: void;
  open_full_disk_access_settings: void;
  open_location_settings: void;
  open_microphone_settings: void;
  open_screen_recording_settings: void;
  open_settings_window: void;
  open_speech_recognition_settings: void;
  open_voice_hud: unknown;
  reconcile_watcher_config_user_cmd: boolean;
  request_accessibility_permission: boolean;
  save_watcher_config_cmd: void;
  set_voice_hotkey_settings: unknown;
  show_main_window: void;
  show_native_microphone_permission_dialog: boolean;
  show_native_speech_recognition_permission_dialog: boolean;
  sidebar_get_main_state: unknown;
  sidebar_navigate: void;
  sidebar_set_width: void;
  start_native_speech_recognition: void;
  start_watcher: unknown;
  stop_native_speech_recognition: void;
  stop_watcher: unknown;
  sync_computer_activity_now: unknown;
  update_voice_hud_state: void;
  vault_compare_and_swap: unknown;
  vault_get_record: unknown | null;
  vault_get_status: unknown;
  vault_initialize: unknown;
  vault_list_deletion_receipts: Array<unknown>;
  vault_list_migration_manifests: Array<unknown>;
  vault_list_records: Array<unknown>;
  vault_list_records_page: unknown;
  vault_put_deletion_receipt: unknown;
  vault_put_migration_manifest: unknown;
  vault_put_record: unknown;
  vault_tombstone_record: unknown;
  write_auth_token_to_file: string;
};

export type NativeCommandContract = {
  [K in NativeCommandName]: {
    capability: (typeof NATIVE_COMMAND_CAPABILITIES)[K];
    input: NativeCommandInputs[K];
    output: NativeCommandOutputs[K];
  };
};

export function isNativeCommandName(value: string): value is NativeCommandName {
  return (NATIVE_COMMANDS as readonly string[]).includes(value);
}
