import { Suspense } from 'react';
import { TasksClient } from './tasks-client';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tasks | Ritual',
  description: 'Daily tasks generated by routines, AI, and manual planning.',
};

function TasksLoading() {
  return (
    <div className="flex h-full flex-col bg-white">
      <div className="flex items-center justify-between border-b border-border px-8 py-5">
        <div className="h-8 w-40 animate-pulse rounded-sm bg-muted" />
        <div className="h-10 w-96 animate-pulse rounded-sm bg-muted" />
      </div>
      <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-3 p-8">
        {[1, 2, 3, 4, 5].map((i) => (
          <div key={i} className="h-14 animate-pulse rounded-sm border border-border bg-muted/20" />
        ))}
      </div>
    </div>
  );
}

export default function TasksPage() {
  return (
    <div className="flex h-full flex-1 flex-col overflow-hidden bg-background">
      <Suspense fallback={<TasksLoading />}>
        <TasksClient />
      </Suspense>
    </div>
  );
}
