import { Suspense } from 'react';
import { TasksClient } from './tasks-client';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tasks | Ritual',
  description: 'Daily tasks generated by routines, AI, and manual planning.',
};

function TasksLoading() {
  return (
    <div className="flex h-full flex-col">
      <div className="px-6 pb-4 pt-7 lg:px-8">
        <div className="h-8 w-32 animate-pulse rounded-sm bg-[#f3f3f2]" />
        <div className="mt-4 h-7 w-72 animate-pulse rounded-sm bg-[#f3f3f2]" />
        <div className="mt-3 h-7 w-56 animate-pulse rounded-sm bg-[#f3f3f2]" />
      </div>
      <div className="mx-auto w-full max-w-[1120px] flex-1 space-y-2 px-6 py-4 lg:px-8">
        {[1, 2, 3, 4, 5].map((i) => (
          <div key={i} className="h-8 animate-pulse rounded-[6px] bg-[#f3f3f2]" />
        ))}
      </div>
    </div>
  );
}

export default function TasksPage() {
  return (
    <div className="flex h-full flex-1 flex-col overflow-hidden">
      <Suspense fallback={<TasksLoading />}>
        <TasksClient />
      </Suspense>
    </div>
  );
}
