import { Suspense } from 'react';
import { TasksClient } from './tasks-client';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tasks | Ritual',
  description: 'Daily tasks generated by routines, AI, and manual planning.',
};

function TasksLoading() {
  return (
    <div className="flex h-full flex-col">
      <div className="mx-auto w-full max-w-[1120px] flex-1 space-y-2 px-8 pt-3 lg:px-10">
        <div className="mb-1 h-8 animate-pulse border-b border-[var(--border-subtle)] bg-[var(--surface-raised)]" />
        {[1, 2, 3, 4, 5].map((i) => (
          <div key={i} className="h-10 animate-pulse rounded-[var(--radius-row)] bg-[var(--surface-panel)]" />
        ))}
      </div>
    </div>
  );
}

export default function TasksPage() {
  return (
    <div className="flex h-full flex-1 flex-col overflow-hidden">
      <Suspense fallback={<TasksLoading />}>
        <TasksClient />
      </Suspense>
    </div>
  );
}
