import type { RoutineCreateInput } from './types';
import type { WorkflowDefinition, WorkflowDefinitionCreateInput, WorkflowKind } from '@/lib/workflows/types';

export type AiRoutineTemplate = {
  id: string;
  title: string;
  description: string;
  workflowKind: WorkflowKind;
  cadence: 'daily' | 'weekly';
  hour: number;
  minute: number;
  weekdays: number[];
  tags: string[];
  config: Record<string, unknown>;
};

export const AI_ROUTINE_TEMPLATES: AiRoutineTemplate[] = [
  {
    id: 'weekly_review',
    title: 'Weekly Review',
    description: 'Summarizes priorities, habit drift, calendar load, and loose ends before the next week starts.',
    workflowKind: 'shutdown_review',
    cadence: 'weekly',
    hour: 16,
    minute: 0,
    weekdays: [4],
    tags: ['ai', 'review'],
    config: {
      include_activity_summary: true,
      include_habit_overview: true,
      include_computer_time: true,
      include_weekly_context: true,
    },
  },
  {
    id: 'experiment_check_in',
    title: 'Experiment Check-In',
    description: 'Reviews active experiments, metrics, and next actions on a regular cadence.',
    workflowKind: 'morning_brief',
    cadence: 'weekly',
    hour: 10,
    minute: 0,
    weekdays: [2],
    tags: ['ai', 'experiments'],
    config: {
      include_calendar: true,
      include_streaks: true,
      include_experiments: true,
      include_metric_deltas: true,
    },
  },
  {
    id: 'recovery_review',
    title: 'Recovery Review',
    description: 'Checks sleep, biometrics, workload, and friction signals before planning the day.',
    workflowKind: 'morning_brief',
    cadence: 'daily',
    hour: 8,
    minute: 30,
    weekdays: [0, 1, 2, 3, 4, 5, 6],
    tags: ['ai', 'health'],
    config: {
      include_biometrics: true,
      include_streaks: true,
      include_recovery_context: true,
    },
  },
  {
    id: 'focus_block_scheduler',
    title: 'Focus Block Scheduler',
    description: 'Looks for fragmented workdays and drafts protected focus blocks.',
    workflowKind: 'distraction_spiral',
    cadence: 'daily',
    hour: 9,
    minute: 15,
    weekdays: [0, 1, 2, 3, 4],
    tags: ['ai', 'focus'],
    config: {
      publish_inbox_card: true,
      publish_artifact: true,
      suggest_focus_block: true,
      schedule_focus_blocks: true,
    },
  },
  {
    id: 'metrics_anomaly_scanner',
    title: 'Metrics Anomaly Scanner',
    description: 'Surfaces unusual movement in habits, biometrics, screen time, and finance-adjacent metrics.',
    workflowKind: 'daily_narrative',
    cadence: 'daily',
    hour: 12,
    minute: 0,
    weekdays: [0, 1, 2, 3, 4, 5, 6],
    tags: ['ai', 'metrics'],
    config: {
      publish_inbox_card: true,
      publish_artifact: true,
      scan_metric_anomalies: true,
    },
  },
  {
    id: 'screen_time_review',
    title: 'Screen Time Review',
    description: 'Reviews computer and device time patterns with specific course-correction prompts.',
    workflowKind: 'shutdown_review',
    cadence: 'daily',
    hour: 17,
    minute: 30,
    weekdays: [0, 1, 2, 3, 4],
    tags: ['ai', 'screen-time'],
    config: {
      include_activity_summary: true,
      include_computer_time: true,
      include_screen_time: true,
      suggest_reflection_prompt: true,
    },
  },
  {
    id: 'drop_the_ball_monitor',
    title: 'Drop-the-Ball Monitor',
    description: 'Scans for commitments that have gone quiet and queues a recovery prompt.',
    workflowKind: 'daily_narrative',
    cadence: 'daily',
    hour: 15,
    minute: 0,
    weekdays: [0, 1, 2, 3, 4],
    tags: ['ai', 'follow-up'],
    config: {
      publish_inbox_card: true,
      publish_artifact: true,
      detect_stale_commitments: true,
      suggest_recovery_prompt: true,
    },
  },
];

export function workflowRoutineInput(definition: WorkflowDefinition, template?: AiRoutineTemplate): RoutineCreateInput {
  const weekdays = definition.schedule.send_weekdays || [];
  const isDaily = weekdays.length === 0 || weekdays.length === 7;
  return {
    title: template?.title || definition.name,
    description: template?.description || `${definition.name} generated by Ritual Intelligence.`,
    status: 'scheduled',
    kind: 'ai_workflow',
    trigger_type: isDaily ? 'daily' : 'weekly',
    trigger_config: isDaily
      ? {
          interval: 1,
          hour: definition.schedule.send_hour_local,
          minute: definition.schedule.send_minute_local,
        }
      : {
          interval: 1,
          weekdays,
          hour: definition.schedule.send_hour_local,
          minute: definition.schedule.send_minute_local,
        },
    timezone: definition.schedule.timezone,
    priority: 'medium',
    tags: template?.tags || ['ai'],
    ai_workflow_definition_id: definition.id,
  };
}

export function workflowPayloadForTemplate(template: AiRoutineTemplate, timezone: string): WorkflowDefinitionCreateInput {
  return {
    kind: template.workflowKind,
    name: template.title,
    definition_family: 'routine',
    trigger_type: 'schedule',
    signal_kind: null,
    status: 'scheduled',
    schedule: {
      timezone,
      cadence: template.cadence,
      send_hour_local: template.hour,
      send_minute_local: template.minute,
      send_weekdays: template.weekdays,
    },
    delivery: { channel: 'in_app', publish: true, inbox: true },
    config: {
      ...template.config,
      ai_routine_template_key: template.id,
      ai_routine_template_title: template.title,
    },
  };
}
