/** Generated by scripts/generate-ui-tokens.mjs. Do not edit directly. */
module.exports = {
  colors: {
    border: "hsl(var(--border))",
    input: "hsl(var(--input))",
    ring: "hsl(var(--ring))",
    background: "hsl(var(--background))",
    foreground: "hsl(var(--foreground))",
    primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
    secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
    destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
    muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
    accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
    popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
    card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
    surface: {
      window: "var(--surface-window)", content: "var(--surface-content)", raised: "var(--surface-raised)",
      floating: "var(--surface-floating)", overlay: "var(--surface-overlay)", chrome: "var(--surface-chrome)",
      sidebar: "var(--surface-sidebar)", panel: "var(--surface-panel)", control: "var(--surface-control)",
      "control-hover": "var(--surface-control-hover)",
    },
    text: { primary: "var(--text-primary)", secondary: "var(--text-secondary)", muted: "var(--text-muted)" },
  },
  borderRadius: {
    lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)",
    control: "var(--radius-control)", row: "var(--radius-row)", card: "var(--radius-card)",
    floating: "var(--radius-floating)", dialog: "var(--radius-dialog)",
  },
  boxShadow: { popover: "var(--shadow-popover)", dialog: "var(--shadow-dialog)" },
  fontFamily: { sans: ["FK Grotesk Neue","-apple-system","BlinkMacSystemFont","Segoe UI","Roboto","sans-serif"] },
};
