import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy | Ritual',
  description: 'Ritual privacy policy and data handling disclosures.',
}

const sections = [
  {
    title: 'Introduction',
    paragraphs: [
      'This Privacy Policy explains how Ritual collects, uses, stores, and shares personal information when you use Ritual\'s applications, websites, desktop software, mobile companion applications, integrations, and related services.',
      'Ritual is a behavior-tracking and personal data product. Depending on the features you use, Ritual may process information you enter directly, information generated by your devices, information imported from connected health or wearable providers, computer activity and screen-time information, and financial data obtained through Plaid to support user-selected tracking and analytics features.',
    ],
  },
  {
    title: 'Information We Collect',
    bullets: [
      'Account and authentication information, such as name, email address, account identifiers, and session metadata.',
      'Habit logs, notes, AI chat prompts, imported files, and other content you choose to create or upload.',
      'Health, wearable, and biometric data when you connect providers such as Apple Health, Whoop, Oura, Garmin, or Fitbit.',
      'Financial account, transaction, and spending-rollup data when you connect Plaid for spending tracking.',
      'Desktop activity, screen-time, screenshot, OCR, and local memory/search data when you enable relevant desktop permissions and features.',
      'Device, diagnostic, analytics, and usage information used to operate, secure, and improve the service.',
    ],
  },
  {
    title: 'How We Use Information',
    bullets: [
      'To provide, operate, secure, and improve Ritual.',
      'To authenticate users and maintain accounts and sessions.',
      'To ingest, normalize, store, and display user-selected tracking data.',
      'To generate analytics, trends, rollups, summaries, and other product features.',
      'To support AI-assisted experiences you choose to use.',
      'To troubleshoot errors, detect abuse, and maintain reliability and security.',
      'To comply with legal obligations and enforce applicable terms.',
    ],
  },
  {
    title: 'Health, Wearable, and Financial Data',
    paragraphs: [
      'Health, wearable, and biometric data is collected only when you choose to connect a supported provider or enable a supported sync path.',
      'If you connect Plaid, Ritual may process institution metadata, account metadata, normalized transaction records, and derived daily spending totals. Ritual currently uses Plaid-backed data for the narrow purpose of helping users track spending as a Ritual habit or behavior.',
      'Ritual does not sell personal information and does not use Plaid-derived financial data for advertising or cross-context behavioral advertising.',
    ],
  },
  {
    title: 'How We Share Information',
    paragraphs: [
      'Ritual may share information with service providers and subprocessors that help operate the service, including providers that support authentication, hosting, database infrastructure, analytics, AI features, error monitoring, and financial connectivity.',
      'Examples of provider categories used by Ritual may include Clerk for authentication, Plaid for financial connectivity, Turso for database infrastructure, Tinybird for analytics processing, hosting providers such as Vercel, AI model providers for AI features you choose to use, OpenPanel for product analytics, and Sentry or similar tools for reliability monitoring.',
      'Ritual may also share information when required by law, to protect rights and security, at your direction, or as part of a business transaction subject to appropriate safeguards.',
    ],
  },
  {
    title: 'Data Retention and Deletion',
    paragraphs: [
      'Ritual retains personal information for as long as reasonably necessary to provide the service, maintain security and reliability, comply with legal obligations, resolve disputes, and enforce agreements.',
      'Retention varies by feature and data type. Disconnecting an integration generally stops future syncs but does not necessarily delete historical data already imported into Ritual unless Ritual specifically processes a deletion workflow or verified deletion request for that data.',
      'Additional details are available in Ritual\'s data deletion and retention policy.',
    ],
  },
  {
    title: 'Your Choices',
    bullets: [
      'Manage connected integrations and sync settings.',
      'Disconnect Plaid and wearable providers.',
      'Control local desktop permissions and privacy-related desktop settings.',
      'Request deletion of certain data or your account, subject to verification and applicable limitations.',
    ],
  },
  {
    title: 'Security',
    paragraphs: [
      'Ritual uses administrative, technical, and organizational safeguards designed to protect personal information. These measures may include authentication controls, multi-factor authentication for critical systems, encryption of sensitive integration tokens, encrypted transport, access controls, monitoring, and other security measures appropriate to the nature of the service.',
      'No method of transmission or storage is completely secure, and Ritual cannot guarantee absolute security.',
    ],
  },
  {
    title: 'Children\'s Privacy',
    paragraphs: [
      'Ritual is not intended for children under 13, and Ritual does not knowingly collect personal information from children under 13.',
    ],
  },
  {
    title: 'Changes to This Policy',
    paragraphs: [
      'Ritual may update this Privacy Policy from time to time to reflect changes to the service, legal requirements, or Ritual\'s data practices. When Ritual makes material changes, Ritual will update the effective date above and may provide additional notice where appropriate.',
    ],
  },
  {
    title: 'Contact',
    paragraphs: [
      'Questions or requests relating to this Privacy Policy or Ritual\'s privacy practices may be directed to Ritual through the contact or support channel made available within the Ritual application or on Ritual\'s website.',
    ],
  },
]

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-white text-gray-900" style={{ fontFamily: "var(--ritual-selected-font-family)" }}>
      <div className="mx-auto max-w-4xl px-6 py-16 sm:px-8 sm:py-20">
        <div className="mb-10 flex items-center justify-between gap-4">
          <Link
            href="/"
            className="text-sm text-gray-500 transition-colors hover:text-gray-900"
          >
            Ritual
          </Link>
          <Link
            href="/data-retention"
            className="text-sm text-gray-500 transition-colors hover:text-gray-900"
          >
            Data retention policy
          </Link>
        </div>

        <header className="border-b border-gray-200 pb-8">
          <p className="mb-3 text-sm uppercase tracking-[0.18em] text-gray-500">Legal</p>
          <h1 className="text-4xl font-medium tracking-[-0.03em] text-gray-950 sm:text-5xl">
            Privacy Policy
          </h1>
          <div className="mt-5 space-y-1 text-sm text-gray-500">
            <p>Effective Date: March 18, 2026</p>
            <p>Company: Ritual</p>
          </div>
        </header>

        <div className="mt-10 space-y-10">
          {sections.map((section) => (
            <section key={section.title} className="border-b border-gray-100 pb-10 last:border-b-0">
              <h2 className="mb-4 text-2xl font-medium tracking-[-0.02em] text-gray-950">
                {section.title}
              </h2>
              {section.paragraphs?.map((paragraph) => (
                <p key={paragraph} className="mb-4 max-w-3xl text-base leading-8 text-gray-700 last:mb-0">
                  {paragraph}
                </p>
              ))}
              {section.bullets ? (
                <ul className="space-y-3 text-base leading-8 text-gray-700">
                  {section.bullets.map((bullet) => (
                    <li key={bullet} className="flex gap-3">
                      <span className="mt-[0.72rem] h-1.5 w-1.5 flex-none rounded-full bg-gray-900" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              ) : null}
            </section>
          ))}
        </div>
      </div>
    </main>
  )
}
